### ISSUE TITLE
Amiga hdf m3u

### ISSUE THREAD

**Issue by remussek** [OnionUI/Onion#145]
is m3u working, or what is the correct syntax. I have hdf files and I'd like to load them at the same time. It doesn't happen what I'm doing wrong

**Comment by Olywa** [comment]
Hi there, this is an old issue that was temporarily lost with our github transition and now restored. Perhaps you solved this already now but the syntax for m3u can be found in the cores official documentation here: 
https://docs.libretro.com/library/puae/

We are also planning on introducing a new version of Amiga Puae (the Puae2021 core) in a future release which will add support for zips so that multi disk games can be contained within a single file.
