### ISSUE TITLE
Aspect ratio change not working

### ISSUE THREAD

**Issue by Flame69chaos** [OnionUI/Onion#149]
I wanted to ask about the aspect ratio settings in the NES and Sega Genesis cores (FCEUmm, Genesis Plus GX). I try to change in Video - Aspect Ratio to different settings - 4:3, 8:7 (PAR). Nothing changes. It only works if you change it in the Scaling menu and set Keep Aspect Ratio to ON. But that's still not the case. Does everyone not change the ratio in the cores or just me?

**Comment by Olywa** [comment]
This is an old issue that was temporarily lost with the github transition, and since restored. 

I suspect you have moved on form this but for anyone looking please visit our [FAQs Sections](https://github.com/OnionUI/Onion/wiki/Frequently-Asked-Questions-%28FAQ%29#how-can-i-change-a-games-scaling-or-make-it-fullscreen). 

Some cores may feature additional aspect ratio related settings within the RetroArch 'Core Options' menu.
