### ISSUE TITLE
Shoulder buttons completely backwards in DOSBOX-Pure

### ISSUE THREAD

**Issue by RetroBreeze** [OnionUI/Onion#159]
I've been testing DOSBOX and have found that the shoulder button mappings are incorrect when device type is set to "Mouse with Left Analog Stick" or "Mouse with Right Analog Stick"

R is actually L2
L is actually R2
L2 is R
R2 is L

So, if I set R to "left click", I will actually need to press the L2 button to perform a left click.

**Comment by Olywa** [comment]
Hey @RetroBreeze, this issue was unfortunately lost (temporarily) due to the transition from old to new github repository but it has now been restored! 

I just watched your DOSBox video (made after you raised this) and didn't see this mentioned, although you did highlight how many games auto detect the correct remaps. I do not have DOSbox setup but are your above suggested remaps still necessary in Onion V4? If so would you mind sharing the default remap file and we can add it to the release?

Many thanks
