### ISSUE TITLE
gamelist/miyoolist show up as games

### ISSUE THREAD

**Issue by Tortugasss** [OnionUI/Onion#21]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/Sichroteph/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

3.12.3

### Miyoo Firmware Version

202204190828

### Provide a clear and concise description of the issue

1. They show up in some console lists as games, not in others. My current miyoolist for GB wasn't visible as a game for example, after scrolling all the games, it is there now. But it's not there in SNES as a game (yet). It is on most consoles though. Not sure what's happening here, but they shouldn't register as launchable games.
 
2. Had an issue with an average sized gamelist.xml which bricked Onion when i launched it. Menu and power weren't responding and restarting auto-launched it. Had to delete the file from the card to stop it from startup-launching and regain access in onion.

### Steps to Reproduce

1. Add gamelist/miyoolist xml's and scroll console game lists all the way. (Not sure what's going on with this, but they mostly show up there)

2. Not sure, but getting a big gamelist.xml and launching it as a game might do the t(b)rick.

### Provide any additional context or information that may help us investigate your issue

N/A

**Comment by Olywa** [comment]
OK, this is solvable....
They are showing up (as games) in the lists for some systems (and not others) as you can configure which extensions are visible. 

Taking your example of SNES, if you open `\Emu\SFC\config.json` you will see the line `"extlist":"sfc|SFC|smc|SMC|zip|ZIP|7z|7Z"` this tells the OS to only present these specific extensions. Note that file names/extensions are case sensitive which is why each appears twice. Some systems have been pre-populated but many are still on the to do list* but configurable by the user.

By contrast if you look at NES (open `\Emu\FC\config.json` ) you will see the line is empty and so it will not filter and instead present _everything_ it finds in the rom folder (including XML files).

You can add necessary extensions (for the roms you have) to any systems config.json with an empty extlist following the example above.

Re your second point, I think you are the first I've seen try to launch an xml with an emulator, it seems it's not a good idea ;)

If you make changes to a lot of configs then I highly recommend making a local backup of your \Emu\ folder in case of upgrades later where things could get overwritten (in fact it's always a good idea to back up the whole SD if you have space). 

I'm closing this as a config issue but it is known and in the future I hope we will reach a point where all main consoles/systems will already have the extlist pre-populated.
