### ISSUE TITLE
DOSBox Pure audio issues when setting Force 60fps

### ISSUE THREAD

**Issue by daedalia** [OnionUI/Onion#225]
The core version included with Onion reports as 0.21. Looking on the DOSBox pure repo the audio issue for this option was fixed in version 0.23. Would it be possible to use a higher revision of the core? Is it recompiled for the Mini to be more efficient? Thank you.

**Comment by Olywa** [comment]
Hi there, this issue was temporarily lost with our github transition but has now been restored. I'm not sure if you are still interested in this?

The included cores _are_ compiled specifically for the Mini, however, we welcome user input if there are improvements to be had by swapping out a core and it looks like there is already an Arm7 release on the DOSBox pure repo that _should_ work.

If you would be interested in testing this for us just backup (or rename) the existing DOSBox pure core and info file in `RetroArch\.retroarch\cores` and add those in the attached. 
[dosbox_pure_libretro-linux_arm7-0.9.7-1.zip](https://github.com/OnionUI/Onion/files/9660469/dosbox_pure_libretro-linux_arm7-0.9.7-1.zip)
