### ISSUE TITLE
Issue Title

### ISSUE THREAD

**Issue by Captainzilla418** [OnionUI/Onion#564]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.03

### Miyoo Firmware Version

202204190828

### Provide a clear and concise description of the issue

i have been using the ps1 emulator with stock bios and any time i try to play abs oddity and abes exiodues it will not show up no matter the format and the only format that works is chd but when i boot into the game i get to the main start screen and none of the controls work if you want to re-create this then use vimm lair that's where i get my files from them and used chdman to try a diffrent format

### Steps to Reproduce

download Oddworld: Abe's Oddysee from vimm any version of the game and put the bin/cue files in a folder in your os rom folder then boot up the miyoo mini. refresh roms then try finding the game it will not show up and if you want to try chd just follow a tutoiral 

### Provide any additional context or information that may help us investigate your issue

chd tutorial https://www.youtube.com/watch?v=5DdSP1KxzSE

**Comment by Olywa** [comment]
Hi, for the games not showing up in the first place, this may be because of the apostrophe in `Abe's`, you should rename and refresh your roms ([see here for related guidance](https://github.com/OnionUI/Onion/wiki/Emulators#rom-files)).

A quick google suggests that the Oddworld controls appear to be problematic with the PCSX-Rearmed core across several devices. This is not an Onion OS issue or something the Onion team can fix (as indicated in the first checkbox you ticked above). You might want to log this with [the core developer](https://github.com/notaz/pcsx_rearmed).

Fortunately, there seem to be some workarounds ([per responses in this thread](https://www.reddit.com/r/MiyooMini/comments/xmd131/i_need_help_miyoo_brethren/)) including sourcing the European version of the game or apparently mapping the controls in Retroarch. If you sourced your game from vimms it will be the USA version (known to exhibit this issue).
