### ISSUE TITLE
Genesis games not being listed as .BIN in main menu, only they are zipped

### ISSUE THREAD

**Issue by lvanjaarsveld** [OnionUI/Onion#569]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

v4.0.3

### Miyoo Firmware Version

202204190828

### Provide a clear and concise description of the issue

When setting up Genesis ROMS on my miyoo I placed extracted .BIN ROMS in the /Roms/MD folder. The games where not indexed or listed. However, I was able to browse them and play using RA directly. 

Then I placed the identical ROMS zipped in the /Roms/MD folder, which listed them in the main menu. 

### Steps to Reproduce

1. place extracted .BIN ROMs in the Genesis folder /Roms/MD
2. go to the main menu, and detect your ROMS are not listed
3. zip the same ROMS
4. go to the main menu and detect the ROMS being listed

### Provide any additional context or information that may help us investigate your issue

I think the issue is clear, nothing to further detail. Let me know if there are any questions.

**Comment by Aemiii91** [comment]
The `bin`/`cue` format (usually generated by PowerISO or similar programs - [more info](https://www.poweriso.com/tutorials/open-bin-cue-file.htm)) is somewhat problematic.

Due to the way the built-in menu system indexes files, we need to either select the `bin` or `cue` file extension. Since the standard format can have multiple `bin` files associated to a single `cue` file, we have chosen to index `cue` files - this avoids duplicate entries.

Unfortunately, many romsets only contain `bin` files, where you need to either generate the `cue` files (there's a [cue generator here](https://www.duckstation.org/cue-maker/) - also works with Genesis games), or change the indexing config for the system:
- To change indexing of `bin` files edit the `Emu/MD/config.json` file in a text editor.
- In the `extlist`, replace `cue|CUE` with `bin|BIN`.

Furthermore, for Genesis games we recommend using zipped `md` files - if you can.
