### ISSUE TITLE
Low battery red border flickers

### ISSUE THREAD

**Issue by zebramonkeylizard** [OnionUI/Onion#575]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.03

### Miyoo Firmware Version

202204190828

### Provide a clear and concise description of the issue

The low battery red border flickers. The bottom half of the border flickers more than the top. I observed it while playing PSX and NES games, and in the main ui. 

### Steps to Reproduce

Let the battery run down to 15%, the default setting, to activate the red border low battery warning. Play some games and navigate the main ui.

### Provide any additional context or information that may help us investigate your issue

Also encountered the issue with the warning set at 20%. I didn't test any others.

**Comment by Olywa** [comment]
Hi there, I've checked this with the devs and the flicker is a side effect of the border draw speed. 

Drawing the border faster would look nicer and remove flicker but it will come at a price and also impact game performance. Given the limited resources of the hardware this was a performance compromise in order to bring this feature while still allowing you to play unhindered. 

I've not seen anyone else raise this as a concern and there are no plans to change it but of course you can lower the percentage or disable the border altogether if you prefer.

**Comment by zebramonkeylizard** [comment]
As it is, the flickering is a distraction. As it does not flicker on the top half of the screen can it be changed to just be a line at the top?
