### ISSUE TITLE
position notifications does not work

### ISSUE THREAD

**Issue by yhusei** [OnionUI/Onion#592]
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.0.3

### Miyoo Firmware Version

none

### Provide a clear and concise description of the issue

when wanting to change the position of the notifications such as (FPS) this does not seem to work, in the same way the background of the notifications. The only thing that works is the color. I already tried to apply and save the changes and nothing.

### Steps to Reproduce

- open retroarch menu
- go to screen layout and notifications
- choose a value to move notifications to the right or left.

### Provide any additional context or information that may help us investigate your issue

none

**Comment by Olywa** [comment]
This is known. Because the Mini does not have a GPU, some RetroArch features have been removed or limited to a barebones implementation (e.g. OSD, Overlays, Shaders) in the Onion build. 

These things come at a performance cost and impact the overall user experience as we are dependant on only the CPU. 

I will ask @schmurtzm to comment since he is closer to the RA build but the OSD was implemented by eggs before him and I don't believe it can be easily updated to enable these options.
